# Generated by Django 5.2.7 on 2025-10-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_zh',
            new_name='name_zh_hans',
        ),
    ]
