# Generated by Django 5.2.7 on 2025-10-21 08:41

import category.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp']), category.utils.check_image_size]),
        ),
    ]
