# Generated by Django 5.2.7 on 2025-10-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_socialmedia_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField()),
                ('awards', models.PositiveIntegerField()),
                ('successfully_operations', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomepageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_patients', models.PositiveIntegerField()),
                ('wards', models.PositiveIntegerField()),
                ('awards', models.PositiveIntegerField()),
                ('ambulances', models.PositiveIntegerField()),
            ],
        ),
    ]
