# Generated by Django 5.2.7 on 2025-10-24 05:15

import category.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_footerstats_homepagestats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='email2',
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP']), category.utils.check_image_size]),
        ),
    ]
