# Generated by Django 5.2.7 on 2025-10-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_remove_email_email2_alter_email_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='number2',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='work_time2',
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.JSONField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='work_time',
            field=models.CharField(),
        ),
    ]
